### ISSUE TITLE
couple things

### ISSUE THREAD

**Issue by wishfoundry** [develpr/zencoder#1]
Hi @shoelessone, 
Congradulations on your first L4 project, hope it's one of many.

Since you pinged me directly regarding this project, I'm going to assume you wanted some feedback. Take/Ignore as you see fit:
1. /vendor folder needs to be inlcuded in .gitignore
2. ZencoderController probably should not extend \BaseController for better package isolation
3. migration should be renamed
4. improve semantic naming of encodings(e.g. Config::get('zencoder::encoding.mp3) vs. Config::get('zencoder::encoding.schemes.1)
5. the files in models prolly belong in src/Develpr/Zencoder and should be re-namespaced to match
6. alias prolly should be: 'Zencoder' => 'Develpr\Zencoder\Zencoder'

[Feature Request]
support for rackspace cloudfiles

**Comment by develpr** [comment]
Hey, thanks a ton for the feedback! I VERY VERY much appreciate it at this point, I'm learning about 3 different tools at once and am sure there will be much room for improvement for a while to come. I'm going to try to incorporate your feedback over the weekend. 

As for pinging you, I'm now very happy I did, but a big part of the reason I did is that you (and a few others!) helped me get even this basic code in place last night on #laravel in IRC, so I just wanted to say thanks and give some credit :).

Thanks again!

**Comment by develpr** [comment]
Small question @wishfoundry re: #6 - can you explain this one to me? My thought was that you meant that to help prevent collisions with other packages that might be called Zencoder (very possible considering it's a popular service), I should add more specificity to my namespace. BUT, it looks like composer builds the autoload_classpath.php file to expect the Zencoder namespace for some reason, ie

``` php
'Zencoder\\Zencoder' => $baseDir . '/src/models/Zencoder.php'
```

I'm not sure how composer decides on this namespace in the autoload_classpath.php or if there is a way I should update this, but for now it seems like Zencoder is the namespace that works?

Also, re #5, somebody on IRC told me that Taylor put his classes in directories like this (models/controllers) so that's why I chose to do that.

**Comment by wishfoundry** [comment]
My thought was to help you follow PSR0 standards so that you have less confusing code
https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-0.md

php doesn't care where the file is located, just so long as it's loaded. php only sees it by it's namespace -> classname. 
PSR0 basically states the namespace should be the same as the folder structure, for easier code organiztion an autoloading.
You have set classmap src/models in your composer.json, which is the equivalent of "automagically figure out what the heck I did and just load it". If you removed the namespace in Zencoder.php composer would map this:

``` php
'Zencoder' => $baseDir . '/src/models/Zencoder.php'
```

it is completely careless about folder structure, and will wheck check subfolders and build you a map.
(which is why you have to dump-autoload ever time you add a new file to classmapped folders, they have no way of know where that file should be)

#5. Taylor has never put his classes in the models dir. IRC lied!

**Comment by develpr** [comment]
I've moved things around a bit:

I've added the Develpr/Zencoder namespace, and moved the controller and models into the src/Develpr/Zencoder directory, and updated my aliases to match.

I also add more semantic encoding names - in the end though I expect (certainly indend!) for developers to create their customer encoding settings, at which point they can and should name the things whatever they want.

I'd like to put my files in a better folder structure (i.e. src/Develpr/Zencoder/models/\* or src/Develpr/Zencoder/controllers/*) but I'm not sure if this is appropriate or not. It seems better then just having all of my files in a flat directory structure, but perhaps not?

**Comment by wishfoundry** [comment]
do you think the interface feels a little weird?

How about something like

``` php
Zencoder::create(Input::get('videofield') );
```

with the create method defined more like

``` php
public static function create($input, $options = array(), $outputName = "" )
{
        if( $outputName == "" ) $outputName = $input->name; //I forget ATM how to call this
        if( is_string($options) $options = Config::get('develpr/zencoder::encodings'.$options);
        if( empty($options) $options = Config::get('develpr/zencoder::encodings.default');

        $newZencoderFile = new ZencoderFile();

        $newZencoderFile->status = 1;
        $newZencoderFile->original_filename = $input;

        if($newZencoderFile->run($options->encodingScheme))
        {
            $newZencoderFile->save();
            return $newZencoderFile;
        }

}
```

**Comment by develpr** [comment]
I think some of that abstraction would be great, but assuming I'm understanding correctly that you're suggesting we just allow them to pass in file upload info from a form, I'm not sure about that as at the end of the day some people may prefer or for whatever reason have files somewhere else (already on Amazon, etc) and it seems to be like it makes most sense to allow them to handle the file uploads however they want, then to just pass in the name of the file that needs to be encoded.

That said, I do agree, it's a bit "weird".

**Comment by wishfoundry** [comment]
I wasn't suggesting that you handle form input directly(although that would feel very laravel-ish)
I was suggesting that the interface be more minimal, with sensible defaults that can be easily overridden.
