### ISSUE TITLE
Video Encoding not working

### ISSUE THREAD

**Issue by codebryo** [develpr/zencoder#5]
Hi, I wanted to say thanks for creating this bundle. But I got some issues and I am note sure if I am using things totally wrong.

When I want to encode a video I allways get returned that there is no object. 

http://d.pr/i/cUv9

I was using the standard settings, encoding example number 2 and set the path for FTP connection. You have any idea if I miss something ?

**Comment by develpr** [comment]
Hey, sorry its taken me so long to get back to you. To double check, are you using this with laravel 3 or are you using the l4 branch with laravel 4?either way ill see what I can figure out tomorrow! Sorry again for delay!

**Comment by codebryo** [comment]
I am using L3 Version. I was able to surpass the thing by adding error-reporting 0 somehow it works for now but I don't think thats the way it supposed to work.

Am 31.01.2013 um 09:26 schrieb develpr notifications@github.com:

**Comment by develpr** [comment]
Sure enough, a terrible small, but terribly important bug. There was a trailing comma in the second (default!) encoding configuration in config/encoding.php and this was causing json_decode to fail as it was not a valid/well formed json object. Note the comma at the end of 

```
    //Video for mobile devices
    2 => '{
        "audio_bitrate": 128,
        "audio_sample_rate": 44100,
        "height": 480,
        "width": 640,
        "max_frame_rate": 30,
        "video_bitrate": 1500,
        "h264_level": 3,
        "format": "mp4"
        },
    ',
```

I've removed this and committed the fix, you should be "good to go" if you pull the latest change set. I also made it slightly more clear where to put the FTP info (`'base_url'`). 

Sorry about the trouble, thanks for letting me know about this!
