### ISSUE TITLE
Thumbnail

### ISSUE THREAD

**Issue by codebryo** [develpr/zencoder#6]
Hey, I have another thing I would like to request. Maybe its allready possible but wasn't able to figure out a easy way to extend the output json for telling zencoder to also return a thumbnail for the encoded Video.  Is there a easy solution ? No matter if its hacked in at first.

**Comment by codebryo** [comment]
I was able to make things work correctly. I will try to make a pull request asap

**Comment by develpr** [comment]
OK, I went ahead and added some basic support for thumbnials. Feel free to submit a pull request and change things, but the feature is there and allows you to specify either how many thumbnails should be created, or at which intervals they should be created.
